---
- name: "Update/setup WSL hosts"
  hosts: "wsl_group"
  become: true
  gather_facts: true

  vars:

  roles:

  pre_tasks:

  tasks:
    - name: "Install dnf packages"
      ansible.builtin.dnf:
        name: "{{ dnf_packages }}"
        state: "present"
      register: "install_output"

    - name: "Show install_output"
      ansible.builtin.debug:
        msg: "{{ install_output.results }}"
      when: install_output.changed

    - name: "Install flatpak packages"
      community.general.flatpak:
        name: "{{ flatpak_packages }}"
        state: "present"
      register: reg_flatpak_packages

    - name: "Update installed flatpaks"
      ansible.builtin.command: "flatpak update --noninteractive"
      register: reg_flatpak_update
      ignore_errors: true

    - name: "Flatpak output"
      ansible.builtin.debug:
        msg: "{{ item.stdout }}"
      loop:
        - "{{ reg_flatpak_packages }}"
        - "{{ reg_flatpak_update }}"
